### ISSUE TITLE
How does this work

### ISSUE THREAD

**Issue by Owen-Pinguenet** [3tch-a-sketch/Seneca-Bot#1]
I don't understand how to run this

**Comment by RafaelCryptycal** [comment]
I also can't figure out how to run it could you make a tutorial video or something?

**Comment by 3tch-a-sketch** [comment]
This repo is currently outdated for the new builds of seneca and as such doesn't work if you want to fork and fix it go a head but it probably won't be recieving anymore updates atleast until I or @MatthewIsAwesome have a use for it again.
