### ISSUE TITLE
Can you make a tutorial on how to use this please.

### ISSUE THREAD

**Issue by Nyal1** [3tch-a-sketch/Seneca-Bot#2]
Many of us would appreciate it if you made a tutorial on how to use this, as it takes me to my course but does not do anything after.

**Comment by 3tch-a-sketch** [comment]
See other

**Comment by MatthewIsAwesome** [comment]
Note: This is a discontinued project with limited functionality. You can read the code to understand how it works but it likely won't work with the latest versions of Seneca.
